version: "2"
services:
  mongodb:
    container_name: mongodb
    build: ./mongo-seed
    command: mongod --smallfiles
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: always
    build: .
    environment:
      URL: mongodb://mongodb:27017
    links:
      - mongodb
    depends_on:
      - mongodb